### ISSUE TITLE
No memory checking, allocz definition causes seg fault

### ISSUE THREAD

**Issue by ant1441** [ghostflame/ministry#1]
The definition of allocz at [utils.c#L25](https://github.com/ghostflame/ministry/blob/master/src/utils.c#L25):

`return memset( malloc( size ), 0, size );`

If the `malloc` fails, the attempt to memset will immediately cause a segmentation violation.
Is there a reason that `calloc` isn't used for zeroed memory?

Further, it doesn't seem like any of the memory allocations are checked or failure dealt with.

**Comment by ghostflame** [comment]
A slight anachronism on my part - code copied in from earlier projects.  So, not all distributions of linux automatically zero'd memory and malloc/memset showed considerably better performance than calloc (and when I first started using allocz, not all distributions were guaranteed to zero memory when it was reallocated having been freed, only the first time it was allocated to this process).

I don't believe that the crash bug is in here - malloc does pitch up specific errors about not being able to allocate.  But I'll address it anyway, in case the next is here...

**Comment by ant1441** [comment]
Would we be seeing an error with memset being called on NULL? A quick test:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char const* argv[])
{
    size_t bytes = 10000000000000000;
    void* p;

    printf("Allocating %zu bytes\n", bytes);
    p = malloc(bytes);
    printf("Allocated %zu bytes to %p\n", bytes, p);
    memset(p, 0, bytes);
    free(p);
    printf("Freed %zu bytes to %p\n", bytes, p);

    return 0;
}                                                   
```

and

```
$ ./min_mem 
Allocating 10000000000000000 bytes
Allocated 10000000000000000 bytes to (nil)
Segmentation fault (core dumped)
```

**Comment by ghostflame** [comment]
Ran a speed test - calloc( 1, size ) is faster, though just barely.  That is a change from when that function first got written (which, I'll wager, is about 2001).  I'd kind of kept it, rather than keep up with who is actually zeroing memory and who isn't.

Returning a pointer to a signature array of bytes that should make calloc failures easy to track down.
